- key: disk_smart
  title: "disk smart"
  fields:
    - name: timestamp
      type: date
      required: true
    - name: sender
      type: keyword
    - name: type
      type: keyword
    - name: disk_path
      type: keyword
    - name: temperature_celsius
      type: long
